version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../src:/var/www
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ../src:/var/www
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/my.conf:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: webapp
      MYSQL_ROOT_PASSWORD: password
